### ISSUE TITLE
Store does not seem to work

### ISSUE THREAD

**Issue by hbj** [diamondio/better-queue#24]
Hi, I have tried using the SQLite store, but the tasks do not seem to be persisted. When I push a new task to a queue, and the task is failing, I expect to find it in the database, at least between task executions, but it's not the case, the table in the db is always empty. I tried to understand what's going on and found out that the release lock function is being called after every run and in the store it's implemented to delete the task from the db. Is that correct? Why is the task not held in the database between executions to make it survive app restarts?

The behavior I expect is actually that a task remains in the db until it finishes or fails after max retries.

**Comment by leanderlee** [comment]
Are you calling the callback without an error? The only time we remove the task from the store is if the task was completed.

**Comment by hbj** [comment]
Yes l'm, and it's also retrying as expected but it's not in the db. If for example I stop and rerun the app during retries, the task is lost.

**Comment by hbj** [comment]
I'm currently using the following workaround, but out of the box it definitely doesn't work for me:

```js
function createQueue(handler, options, tableName) {
  const store = new SQLStore({
    dialect: 'sqlite',
    path: config.databaseLocation,
    tableName
  });

  store.releaseLock = function releaseLock(lockId, cb) {
    cb();
  };

  const opts = Object.assign({}, options, {
    store,
    maxRetries: config.jobs.maxRetries,
    retryDelay: config.jobs.retryDelay * 1000
  });

  const queue = new Queue(handler, opts);

  queue.on('task_finish', (taskId) => {
    log.trace(`${tableName}: Task with id '${taskId}' finished.`);
    store.deleteTask(taskId, () => {});
  });

  queue.on('task_failed', (taskId, err) => {
    log.warn(`${tableName}: Task with id '${taskId}' failed.`, { err });
    store.deleteTask(taskId, () => {});
  });

  return queue;
}
```

I have also noticed that it's not possible to use different tables in the same database for the different queues because access to the database is not synced across queues and we get many access errors because the table is locked.

**Comment by andrewferrier** [comment]
I have exactly the same issue. No task persistence, even between retries.

**Comment by andrewferrier** [comment]
One of the things that's very confusing here is that there appear to be *two* stores which can be used for sqlite: https://github.com/diamondio/better-queue-sqlite and https://github.com/diamondio/better-queue-sql. I *think* I'm using the second one with `dialect: sqlite`.

**Comment by wedgwood** [comment]
@andrewferrier I thought the first one better. Because the second one use `knex` as `sqlite` connector, and the script would be not stopped automatically after nothing to do for `knex`'s implementation.
