### ISSUE TITLE
webpack

### ISSUE THREAD

**Issue by retorquere** [diamondio/better-queue#26]
I'd like to use better-queue through webpack, but it dynamically requires the memory store as a fallback. Would it add too much overhad to always require memory store statically, and just not use it when overridden?

**Comment by retorquere** [comment]
Worked by just passing the store explicitly.

**Comment by inciteio** [comment]
@retorquere can you provide an example of how you solved this issue? I am not sure what you mean by "Worked by just passing the store explicitly".

**Comment by retorquere** [comment]
```
import Queue = require('better-queue')
import MemoryStore = require('better-queue-memory')

var q = new Queue(function (input, cb) {
  
  // Some processing here ...

  cb(null, result);
},
{
    store: new MemoryStore(),
  }
)
...
