### ISSUE TITLE
Safe to replace setImmediate with setTimeout?

### ISSUE THREAD

**Issue by retorquere** [diamondio/better-queue#27]
I am trying to use a webpacked version of better-queue in a Firefox extension, and it looks like setImmediate doesn't work in Firefox. Is it safe to replace all calls to setImmediate with setTimeout? I've tried reading the docs on the JS event loop, but it's not clear to me what the potential downsides are of using setTimeout for better-queue.

**Comment by LinusU** [comment]
It could potentially slow things down by a short amount, I would recommend using something like [asap](https://www.npmjs.com/package/asap) instead of `setTimeout`

```js
if (typeof window.setImmediate !== 'function') {
  window.setImmediate = require('asap')
}
```

**Comment by LinusU** [comment]
Although I don't think that there will be any noticeable performance regression by using setTimeout, maybe we should just use [`set-immediate-shim`](https://github.com/sindresorhus/set-immediate-shim) directly in the code here... how do you feel @leanderlee?

**Comment by retorquere** [comment]
AFAICT webpack already tries to bring in [setimmediate.js](https://www.npmjs.com/package/setimmediate), but it's not taking -- if I just replace `setImmediate` with `setTimeout` in `better-queue` after installing it into `node_modules` before running webpack, my tasks do trigger, but without it (and with the `setimmediate.js` that webpack tries to bring in) they don't.

I've tested for the existence of `setImmediate` in my code and it does find it as a function, yet my tasks never go beyond `task_queued`; when I replace `setImmediate`, I see the queue callback firing. I have tried replacing the calls in `better-queue` with calls to `setImmediateShim` and I see no change in behavior. Replacing `setImmediate` with calls to `asap` does work.

Firefox extensions present a slightly odd runtime environment; some things work node-ish, some things work browser-ish, and because of that, webpack sometimes gets it wrong (`window` isn't necessarily global across all UI elements for example, and a lof of shimming depends on it being global). I may have to use [graspjs](http://www.graspjs.com/) to patch better-queue after install to replace setImmediate rather than shimming setImmediate.

**Comment by retorquere** [comment]
(I take it when you say "it could potentially slow things down" you man the 4ms clamp on `setTimeout`? That is acceptable for my use-case -- if anything, I need rate limiting more than sub-4-ms control)

**Comment by retorquere** [comment]
if `better-queue` were to call `asap` instead of `setImmediate`, things would work for me too, but I don't know about the desirability of that for `better-queue` -- Firefox extensions surely are a very niche concern for the npm world.

**Comment by leanderlee** [comment]
I would prefer not to shim if possible. better-queue was not really made with browsers in mind, but I'm glad to hear it's working for the most part. @retorquere's issue seems to be an issue with the Firefox extension environment than better-queue.

We could allow users to pass in their own setImmediate function through options (defaulting to the global setImmediate), but it will add a tiny performance penalty to all use cases (as @retorquere says, this problem might be rather niche)

**Comment by retorquere** [comment]
I'm just happy to know it's safe to replace setImmediate (right?).

**Comment by retorquere** [comment]
@leanderlee I just got a collaboration invitation for the `better-queue` repo -- I accepted, but this would give me `push` access it turns out. Until we have a very clear idea on what changes would be desirable (if any at all), it's best not to grant me push access I think. Accidents happen.

**Comment by leanderlee** [comment]
It's a little bit hacky, since you wouldn't be able to get upstream changes from better-queue without replacing setImmediate again. If you feel comfortable doing that, it would solve your problem...

**Comment by retorquere** [comment]
It's a little bit hacky, that is true, but my only other option would be to fork, and I *really* don't want that. Or to convince you to call `asap` instead of `setImmediate`.

I currently just have this in my `package.json`:

```
"postinstall": "grasp --in-place --equery 'setImmediate($x)' --replace 'setTimeout({{x}}, 0)' node_modules/better-queue/lib/queue.js"
```

and that should fire every time I install newer versions of `better-queue`. It's fragile against structural changes in `better-queue`, but that should in principle be picked up as collateral damage by my test suite.

**Comment by leanderlee** [comment]
Seems easiest to pass in the setImmediate you would want. See f136e9f291ce8ba6ea0cb81655155ee2437a16df

**Comment by retorquere** [comment]
Much better for me, but I didn't want to presume. Awesome, it's on nmpjs already! Thank you!

**Comment by LinusU** [comment]
Nice!! Great work!

Can we consider this closed now?

**Comment by retorquere** [comment]
Absolutely, and thanks so much. `better-queue` solves a substantial problem in [BBT](https://github.com/retorquere/zotero-better-bibtex) and there really is no substitute for `better-queue` on npm.

**Comment by retorquere** [comment]
I generally don't close issues unless I am requested to do so, leaving that decision to the developer. I'll be happy to close.

**Comment by LinusU** [comment]
Great!

**Comment by retorquere** [comment]
For the benefit of people who may use this in Firefox: you need to pass `setImmediate: setTimeout.bind(null)`, not just `setImmediate: setTimeout` for this to work; the only reference I could find on this is [here](https://bugs.chromium.org/p/v8/issues/detail?id=4718).
