### ISSUE TITLE
callbacks with 1 concurrent job

### ISSUE THREAD

**Issue by chadhamre** [diamondio/better-queue#31]
Is there an obvious reason why my queue doesn't wait for the callback to be executed before starting the next job?

<img width="453" alt="screen shot 2017-12-21 at 3 17 57 pm" src="https://user-images.githubusercontent.com/1864797/34273424-46cd4d44-e662-11e7-8710-4b43a866eb9f.png">

At the end of webhookUpdater(), I call done(), but as the next job is queued, it starts before that happens. Am I misunderstanding something? Also, is there a better place to ask questions like this?

**Comment by Dragomir-Ivanov** [comment]
@chadhamre Can you add more details on how you resolved this closed issue? Thanks.
