### ISSUE TITLE
Have concurrency take function?

### ISSUE THREAD

**Issue by KyleAMathews** [diamondio/better-queue#33]
We've been using better-queue in Gatsby with great success so thanks for the great design! One thing I'd like to add is the ability to change the concurrency of different queues as at different times.

Is this something you've considered? Would be interested in taking? I haven't looked at your code at all so not sure how involved a PR for this would be but if you're interested, I'd be happy to take it on.

**Comment by Dragomir-Ivanov** [comment]
@KyleAMathews What is the status of this issue? I am also interested in dynamically changing the `concurrent` tasks the queue can process. I think the patch will be fairly simple, just a method that will change `self.concurrent` of the Queue object. Obviously this adjustment will take some time, for the currently processing tasks to finish, but for me that is not a problem. 
I guess @leanderlee can advice better.

**Comment by leanderlee** [comment]
It's been a while since I wrote this code, but I think as a hack, you can try changing the `queue.concurrent` and calling `_processNextIfAllowed` to trigger another 'thread'... Let me know if that ends up working!

**Comment by Dragomir-Ivanov** [comment]
@leanderlee thanks for the fast response, man. I will try tomorrow, and if it works will submit a PR. Better-queue is awesome :)
