### ISSUE TITLE
Types Definition

### ISSUE THREAD

**Issue by jbethke** [diamondio/better-queue#37]
**Feature Request**
[better-queue](https://github.com/diamondio/better-queue) lacks a Types definition; either as part of this project or as part of [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/).

Even without types, better-queue works fine with Typescript. Types is simply a "nice to have."

**Steps to Replicate**
`index.ts`
```
import * as Queue from 'better-queue';

let myQueue : Queue = new Queue(fn);
```

tsc build error -> `Could not find a declaration file for module 'better-queue' '/queue.js' implicitly has an 'any' type.`

**Work Around**
Import with:
`let Queue = require('better-queue');`

**Comment by LinusU** [comment]
Happy to review a PR as well!

**Comment by jbethke** [comment]
I'll take ownership of preparing a types definition and provide a PR when ready.

**Comment by ddehghan** [comment]
Do you guys want to review this: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/better-queue

It seems it has been out there for a while. Bringing it into this library makes it easier to update it.

**Comment by jbethke** [comment]
Sorry, my project focus has changed and this dropped off the back of my todo list.

I had put these types together 6 months ago, and it suited my immediate needs; so I never got around to cleaning it up and preparing a proper pull request.
https://github.com/jbethke/better-queue/tree/types-definition/types

It appears someone beat me to it (that's a good thing). For now, I'm preoccupied with something else and unable to properly review the other type definition.
