### ISSUE TITLE
async/await

### ISSUE THREAD

**Issue by ekifox** [diamondio/better-queue#39]
```javascript
function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms))
}

const q = new Queue(async (input, cb) => {
  console.log(input)
  await sleep(1000)
  cb()
}, {
  concurrent: 3
})
```

Now I need to call in async callback functions. Can you do an automatic wait for asynchronous functions? To remove that callback

**Comment by LinusU** [comment]
I would love a 4.x where all callbacks are replaced by Promises ☺️

**Comment by leanderlee** [comment]
Me too! Anyone want to take a shot at it?

**Comment by leanderlee** [comment]
Duplicate of #23

**Comment by nombrekeff** [comment]
> Me too! Anyone want to take a shot at it?

I might have a take on this!

**Comment by njinvozone** [comment]
any update on 4.X ?

**Comment by beautyfree** [comment]
still waiting
