### ISSUE TITLE
Clear tasks in queue

### ISSUE THREAD

**Issue by karmac2015** [diamondio/better-queue#44]
Is there a way to clear all tasks in a queue ? and also clear task by id to remove task from queue before being processed?

**Comment by leanderlee** [comment]
I guess you can make a custom store to do this... It should be fairly trivial to extend the store to include it, but it’s not included in better queue stores currently.

**Comment by karmac2015** [comment]
Your library is good but after using it , I think it is better to provide a way that allows developers to access tickets and workers inside queue, so they can remove tickets and manage workers. There is no full control on tasks that pushed to queue.

**Comment by leanderlee** [comment]
I am not actively developing this project anymore, but would be happy to accept contributions to keep it going. Please feel free to propose and make the necessary changes so our community can benefit from this!

**Comment by crushjz** [comment]
You can clear the queue by calling `queue.cancel(taskId)` for each of the remaining tasks.
The downside is that you have to keep the ids of the tasks and their status somewhere.

eg:
```
const abortQueue = (tasksToStop: string[]): void => {
  tasksToStop.forEach(taskId => {
    queue.cancel(taskId)
  })
}
```
