### ISSUE TITLE
Does it work with karma+jasmine ?

### ISSUE THREAD

**Issue by altinselimi** [diamondio/better-queue#45]
Hi, 
I'm trying to do some asynchronous operations inside a task which resolves when I get the result and complete some manipulations. And its working properly, except when I'm trying to make test cases for it.
Here's a code example:

```
myservice.service.ts
public saveToAPI(url: string, id: string, payload: any): Promise < any > {
        return new Promise((resolve, reject) => {
            this.queue.addTask({
                id: `operation-${id}`,
                task: () => {
                    return this.http.post(url+'/save', payload).toPromise((res) => {
                       //do some operations here
                       resolve()
                    }).catch(err => {
                       reject(err)
                    })
                }
            });
        });
    }

```
myservice.spec.ts

    fdescribe('saveToAPI', () => {
        fit('should save payload to API', (done) => {
            service.saveToAPI('https://myurl.com', 'uniqid', {name: 'John Doe'}).then(res => {
                //expect(res).toEqual(something)
                done();
            }).catch(err => {
                fail(err);
                done();
            });

            const request = httpMock.expectOne(
                'https://myurl.com/save'
            );
            request.flush({
                status: 200,
                data: {
                    'message': 'Saved successfully'
                }
            });
        })
    });
Errors in the console only mention that the httpMock failed to record any request made to the server, and it only happens for functions which use better-queue.

Any ideas ?

**Comment by LinusU** [comment]
Shouldn't you setup the mock _before_ calling `service.saveToAPI`?
