### ISSUE TITLE
issue with concurrency and db store (sqlite)

### ISSUE THREAD

**Issue by jpilon** [diamondio/better-queue#46]
Hello, been using better-queue in production for a long time, works great :)

I'm looking to add some persistence to the queue by way of sqlite. When running a test using:

```
batchsize: 1,
concurrent: 1,
store: {
    type: 'sql',
    dialect: 'sqlite',
    path: '/home/data.db'
},
```

The second multiple items are pushed to the queue in a loop, it always executes 2 items immediately. It should be executing one at a time since concurrency is set to 1. As soon as I remove the store options it works perfectly fine. 

Is there a simple way to fix this?

**Comment by leanderlee** [comment]
Do you have a simple example to reproduce the issue? Thanks

**Comment by jpilon** [comment]
@leanderlee sure no problem, here's a simplified version of what I'm doing. The second items are pushed to the queue it will process the first two items in parallel. It should only process one at a time. If I remove the "store" options it correctly processes one at a time. 

I've also seeing the queue blocking the rest of my app - in the example below I have an http listener where other servers can send json objects so when the queue is empty it will work properly however if the queue is currently running any other incoming http requests hang until the queue completes. I'm not sure what could be causing that issue (this issue happens with / without the store options).

Any help would be great :)

```
const compression           = require('compression');
const express               = require('express');
const http                  = require('http');
const bodyParser            = require("body-parser");
const execSync              = require('child_process').execSync;
const Queue                 = require('better-queue');
const fs                    = require('fs');

var queue = new Queue(function (item, cb) {
    try {
        console.log('begin ', item['name']);
        var file_name = 'random name';
        fs.writeFileSync('/home/data/'+file_name, JSON.stringify(item));
        execSync('docker run --cpus 1.0 --shm-size 1G --rm -v /home/custom_app:/app app:latest '+file_name);
        cb(null, null);
    } catch (err) {
        console.log(err);
    }
    
}, {
    store: {
        type: 'sql',
        dialect: 'sqlite',
        path: '/home/data/app.db'
    },
    concurrent: 1,
    batchSize: 1,
    batchDelay: 0,
    maxTimeout: 60000,
    maxRetries: 10, 
    retryDelay: 500
});

var app = express();
app.use(compression());
app.use(bodyParser.urlencoded({
    extended: true
}));

app.post("/", function (req, res) {
    var items = JSON.parse(req.body.data);
    for(var item of items) {
        console.log('Queue', item.name);
        queue.push(item);
    }
    res.setHeader("Content-Type", "application/json")
    res.send('{"status":"ok"}');
});

```

**Comment by leanderlee** [comment]
Regarding the issue with the store options, it sounds like an issue with the [better-queue-sql](https://github.com/diamondio/better-queue-sql) package. That code has changed a lot and I can't speak to the state of that package, as I was not part of its recent development.

Confusingly, there is also the [better-queue-sqlite](https://github.com/diamondio/better-queue-sqlite) package, which I made a long time ago. You can give that a shot by changing the `type` to be `sqlite` instead of `sql`.

The node process is blocking because you are using synchronous commands in your processing function. You should watch [this talk](https://www.youtube.com/watch?v=cCOL7MC4Pl0) by Jake Archibald, he does a great job at explaining how JS concurrency works.

**Comment by jpilon** [comment]
@leanderlee ok great thanks, I'll check out the other package. Yeah I assumed the blocking was due to synchronous tasks.
