### ISSUE TITLE
What about having access to the task id? 

### ISSUE THREAD

**Issue by nombrekeff** [diamondio/better-queue#49]
### Description
I would need to have access to the task id on push or on queued if this is posible. So I can send it back to the user. I dont know if this is the best aproach... 

**My process goes as follows:**
1. Receive data from user
2. Create data 
3. Push to queue
4. On accepted I should respond to user with the id of the process for later use.
5. User send me the id to retrieve the 

### My Aproach
Now I save them myself with a custom id, so if program restarts they are all lost, It would be really helpfull to be able to use the id from the task.

### Question
Is it posible to get the task id either on queued or on accepted?

**Comment by nombrekeff** [comment]
I just found a way around it, listening to queue `on_accepted` event returns the id of the task as well as the data, so I update the task data to have a `task_id` and when ticket `accepted` events happens its updated with the task_id I want.

```js
let queue = new Queue(task, {});

queue.on('task_accepted', (id, task_data) => {
  task_data.task_id = id;
});


let data = new MyData();
let ticket = queue.push(data);
ticket.on('accepted', () => {
  let task_id = data.task_id; // is set to the correct task id
  // Return to the user
});
```

**Comment by leanderlee** [comment]
In this case, I think you should manage the IDs yourself by passing in an `id` field, or changing the `id` option.

**Comment by nombrekeff** [comment]
Yup, thanks, that's what I ended up doing in the end, passing in the `id`.
