### ISSUE TITLE
Knex:warning - Pool2 - Error: ResourceRequest timed out

### ISSUE THREAD

**Issue by nombrekeff** [diamondio/better-queue#50]
I've come accross this error, when adding a bunch of jobs, any idea why this could be happening?
I can attach code example if needed.

**PD:**
It fires event accepted and then fails.

```js
Knex:warning - Pool2 - Error: ResourceRequest timed out
Unhandled rejection Error: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at C:...\node_modules\knex\lib\runner.js:191:30
    at tryCatcher (C:...\node_modules\bluebird\js\release\util.js:16:23)
    at C:...\bluebird\js\release\catch_filter.js:17:41
    at tryCatcher (C:...\node_modules\bluebird\js\release\util.js:16:23)

```

**Comment by leanderlee** [comment]
This sounds like an issue with `better-queue-sql`, as `better-queue` does not require knex.

**Comment by ivansstoyanov** [comment]
you have multiple processes that write into same sql file
for example two queues or one queue and one sql database service
