### ISSUE TITLE
Duplicate Check?

### ISSUE THREAD

**Issue by schier1987** [diamondio/better-queue#53]
Hi there, 
first of all great package, keep it up!
Sorry to open an issue, didn't know where to ask.

Is there a possibility to print out the current elements in the Q and/or to check if the element about to being pushed is already in the Q? Couldn't find something in the documentation.

Thank you very much!

**Comment by nmargaritis** [comment]
The support you are looking for is there.

Check out the `merge` functionality, through which you can merge duplicate tasks.
```
var counter = new Queue(function (task, cb) {
  console.log("I have %d %ss.", task.count, task.id);
  cb();
}, {
  merge: function (oldTask, newTask, cb) {
    oldTask.count += newTask.count;
    cb(null, oldTask);
  }
})
counter.push({ id: 'apple', count: 2 });
counter.push({ id: 'apple', count: 1 });
counter.push({ id: 'orange', count: 1 });
counter.push({ id: 'orange', count: 1 });
// Prints out:
//   I have 3 apples.
//   I have 2 oranges.
```
To do that you will need to have a common task ID https://github.com/diamondio/better-queue#task-id
