### ISSUE TITLE
Any Sample for worker pulling messages from queue?

### ISSUE THREAD

**Issue by psaxena** [diamondio/better-queue#54]
Hi,

I am looking for in memory queue options in node as i want to avoid installing redis, rabbitmq for queue/worker mechanism.

Current sample shows processing of messages while initializing queue in a process method. Do we have any mechanism in better-queue where workers can pull messages from queue? If Yes, Please point to some example which can be referred.

Thanks

**Comment by nombrekeff** [comment]
I think this is not possible at the moment, but I am not totally sure. Better wait for a maintainer to confirm this.

If  I have a bit of time I will check it for you

**Comment by leanderlee** [comment]
Yes unfortunately we don't support this at the moment. Best you can do is check whether or not the work needs to be completed in the processing function before executing. Perhaps someone would be interested in adding this in as a feature, but it will require changes to the store interface.

**Comment by leanderlee** [comment]
I stand corrected, I believe there is a `queue.cancel(taskId, cb)` call.
