### ISSUE TITLE
404 Gitter Link 

### ISSUE THREAD

**Issue by ManAnRuck** [diamondio/better-queue#60]
the Gitter link goes to a 404 page
looks like in reason of renaming the org/account (previous leanderlee)

<img width="588" alt="Bildschirmfoto 2019-09-25 um 12 35 50" src="https://user-images.githubusercontent.com/2183135/65593594-18276e00-df91-11e9-8ed8-32682759994c.png">

https://gitter.im/leanderlee/better-queue <- this works

**Comment by leanderlee** [comment]
Thanks for the fix!
