### ISSUE TITLE
What is the suggested highest value for concurrent option?

### ISSUE THREAD

**Issue by raeesaa** [diamondio/better-queue#66]
We were planning to incorporate better-queue in our application. Since default value for concurrent option is `1`, execution of tasks is slow. Also, if task takes long time to resolve, new job will not be executed (which is expected behavior) until it is resolved thus increasing wait time for next job.

We would like to execute as many jobs as possible concurrently. Are there any suggestions on highest value that can be set for `concurrent` option given number of CPUs?

**Comment by dipoarowona** [comment]
any update on this?

**Comment by leanderlee** [comment]
I'm confused what the question is... If it's about the maximum concurrent setting, you can use any number up to `Infinity` (in which case why use a queue?)... Your optimal value would be dependent on the workload.

If I'm misunderstanding can you clarify with an example of the issue?
