### ISSUE TITLE
TypeScript Support

### ISSUE THREAD

**Issue by bennyn** [diamondio/better-queue#68]
Hello, I like your library and I would like to use it with TypeScript. Would you welcome a PR committing a TypeScript definition file?

**Comment by leanderlee** [comment]
Of course

**Comment by bennyn** [comment]
Hi @leanderlee, I have noticed that there are already existing TypeScript definitions. It was just not explained in the README, so I created a PR: https://github.com/diamondio/better-queue/pull/69

Ofcourse, it would be nice to have a definition file directly in this repository here but using "@types/better-queue" will work for the beginning. 😊
