### ISSUE TITLE
Delete a task?

### ISSUE THREAD

**Issue by Fossil01** [diamondio/better-queue#94]
Is there any way to delete a task currently in the queue? Trying to convert from BullMQ to this, but I am watching a folder for file changes and when the file gets deleted before the job runs I want to delete the job from the queue.

**Comment by leanderlee** [comment]
It’s been a while since I looked at this repo, but have you tried
`cancel(taskId)`?

https://github.com/diamondio/better-queue#cancelabort

**Comment by leanderlee** [comment]
I believe you can set the ID via an option:
https://github.com/diamondio/better-queue#task-id
